version: '3.8'

services:
  vault:
    image: ${VAULT_IMAGE}
    container_name: vault
    restart: unless-stopped
    ports:
      - "${VAULT_PORT}:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
    volumes:
      - vault-file:/vault/file
      - vault-logs:/vault/logs
      - ./vault/config:/vault/config
      - ./init.sh:/vault/init.sh
    command: >
      sh -c "vault server -config=/vault/config/vault.hcl & 
             sleep 5 && 
             sh /vault/init.sh"
    networks:
      - ${NETWORK_NAME}

volumes:
  vault-file:
  vault-logs:

networks:
  ${NETWORK_NAME}:
    driver: bridge
