version: '3.8'

services:
  redis-vector:
    image: redis/redis-stack:latest
    container_name: redis-vector
    ports:
      - "6379:6379"      # Redis
      - "8004:8001"      # RedisInsight UI
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 900 1
    networks:
      - vector_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  vector_network:
    driver: bridge
