version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "7006:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  pgadmin_data:
