version: '3.8'

services:
  redis-vector:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:6379"      # Redis
      - "${REDIS_WEB_PORT}:8001"      # RedisInsight UI
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 900 1
    networks:
      - vector_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
    

networks:
  ${NETWORK_NAME}:
    driver: bridge
